### ISSUE TITLE
run error when blocking port covert channels

### ISSUE THREAD

**Issue by pluviophilee** [FPSG-UIUC/SPT#1]
Hi,

I'm trying to blocking port covert channels. We set the **moreTransmitInsts** as 1. And, we execute the run_spt.py in Spectre model. However, the simulation never ends. Do you have any idea to deal with this issue?

Any comment is highly appreciated.

**Comment by rchoudhary** [comment]
Apologies for responding so late! For some reason Github didn't inform me that an issue had been posted...

In any case, what program are you testing SPT hardware on?

Also, have you tried running with the `--track-insts` option? It might tell what is causing the simulator to hang.

**Comment by pluviophilee** [comment]
Thank you for replying.

Our command is "build/X86_MESI_Two_Level/gem5.fast --outdir=m5out configs/example/se.py -c test --num-cpus=1 --mem-size=4GB --num-l2caches=1 --l1d_assoc=8 --l2_assoc=16 --l1i_assoc=4 --cpu-type=DerivO3CPU --needsTSO=1 --scheme=SpectreSafeFence --num-dirs=1 --ruby --applyDDIFT=1 --configImpFlow=Ignore **--moreTransmitInsts=1** --ifPrintROB=0 --network=simple --topology=Mesh_XY --mesh-rows=1 --printDelayCycles=0 --enableShadowL1=1 --bottomlessShadowL1=0 --untaintTier=0 --freeParam=3 --disableUntaint=0 --fwdUntaint=1 --bwdUntaint=1 --idealUntaint=0"

And here is the test code:
```
#include<stdio.h>

void aaa()
{
	int t[512*128]={0};
	int flag = 0;
	for(int i = 0;i < 100;i ++){
		if(i < 10){
			flag &= i;
			t[i*512] ++;
			t[i*512] = t[i*512]+flag;
			flag += i;
		}
	}
	return ;
}

int main()
{
	int a = 0,i = 1;
	a ++;
	if(i > 10){
		a &= i;
		
	}
	int temp = a ++;
	for(int j = 1;j < 10;j ++){
		temp &= a;
		a ++;
	}
	aaa();
	return 0;
}
```


We set the **moreTransmitInsts** as 1 to consider div insts. After analyzing the reason of blocking, it seems like several tainted div insts are never untained, then they can not be issued.

**Comment by rchoudhary** [comment]
Thanks! I'll try running that program and see what the issue is.

**Comment by pluviophilee** [comment]
Ok. Thanks : )

**Comment by rchoudhary** [comment]
What flags are you compiling the program with?

**Comment by pluviophilee** [comment]
I have tried to compile it with "-O0" and "-O0 -static". And, my gcc version is "gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ".

**Comment by rchoudhary** [comment]
@pluviophilee Apologies for the late update. PR #2 should fix the issue. Please let me know if this works or if you run into any more trouble!
